wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.27
    code_path: code/train.py
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
    t:
      1:
      - 3
      4: 3.7.0
      5: 0.10.27
      8:
      - 5
